image: "dbisilm/pfabric:alpine"

stages:
  - build
  - test

build:
  stage: build
  tags: 
    - grouprunner
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST_CASES=ON ..
    - make -j 3
    # clean up unnecessary files and strip binaries
    - rm -rf _deps generated
    - strip test/*Test
  artifacts:
    paths:
      - build/
    expire_in: 30 minutes

test:
  stage: test
  tags:
    - grouprunner
  script:
    - cd build
    - ctest -V
  dependencies:
    - build

coverage:
  stage: build
  only:
    - master
  tags: 
    - grouprunner
  script:
    - echo pfpass | sudo -S apk add py-pip
    - pip install gcovr --user
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" -DBUILD_TEST_CASES=ON ..
    - make -j 3
    - ctest -V
    - ~/.local/bin/gcovr -r .. --exclude _deps --exclude '(.+/)?catch\.hpp$'
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
